### ISSUE TITLE
How can I workaround mixed content blocking?

### ISSUE THREAD

**Issue by hedgerh** [soundcloud/waveformjs#18]
I'm writing a Chrome extension that alters the Soundcloud official site.  I am unable to get data from the waveformjs server due to mixed content being blocked.  When I attempt to connect with https, I get an SSL error since the server attempts to identify itself as *.herokuapp.com.

Is there any way to workaround this? I tried to use https://waveformjs.herokuapp.com/w, but it didn't work.

**Comment by alexweinstein** [comment]
+1

**Comment by hedgerh** [comment]
@alexweinstein See my comment above.  It worked well for me for the time being.  They don't seem to maintain this anymore.
