### ISSUE TITLE
What is the technique to create the float array?

### ISSUE THREAD

**Issue by DvirH** [soundcloud/waveformjs#20]
I have mp3 files on my server and I would like to know how to create the float array.
Is Api for it exists?

Thanks.

**Comment by voronianski** [comment]
@kitop @DvirH any well-known js solutions?

**Comment by DvirH** [comment]
@voronianski 
No js solution. 
I used @kitop technique to get the waveform with c#. 
I can share with you the code if you want

**Comment by voronianski** [comment]
@DvirH that's sad :( it will be nice to take a look, thanks.

**Comment by DvirH** [comment]
@voronianski  
Actually there is a solution. But it's not for streaming. It's only for waves which plays local.

Look on this libary: ( Search on the source code how they create the peak array with html 5)
http://www.wavesurfer.fm/
